// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: project-root/grpc/proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_project_root_grpc_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_project_root_grpc_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_project_root_grpc_proto_proto_rawDescGZIP(), []int{0}
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	LogicalTime   int64                  `protobuf:"varint,3,opt,name=logicalTime,proto3" json:"logicalTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_project_root_grpc_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_project_root_grpc_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_project_root_grpc_proto_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ChatMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ChatMessage) GetLogicalTime() int64 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

// message for when a new user joins the chat
type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	LogicalTime   int64                  `protobuf:"varint,2,opt,name=logicalTime,proto3" json:"logicalTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_project_root_grpc_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_root_grpc_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_project_root_grpc_proto_proto_rawDescGZIP(), []int{2}
}

func (x *JoinRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *JoinRequest) GetLogicalTime() int64 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

// message for when a user leaves the chat
type LeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	LogicalTime   int64                  `protobuf:"varint,2,opt,name=logicalTime,proto3" json:"logicalTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	mi := &file_project_root_grpc_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_root_grpc_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_project_root_grpc_proto_proto_rawDescGZIP(), []int{3}
}

func (x *LeaveRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LeaveRequest) GetLogicalTime() int64 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

// message for clients to publish a new chat message
type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	LogicalTime   int64                  `protobuf:"varint,3,opt,name=logicalTime,proto3" json:"logicalTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_project_root_grpc_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_root_grpc_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_project_root_grpc_proto_proto_rawDescGZIP(), []int{4}
}

func (x *PublishRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *PublishRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *PublishRequest) GetLogicalTime() int64 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

var File_project_root_grpc_proto_proto protoreflect.FileDescriptor

const file_project_root_grpc_proto_proto_rawDesc = "" +
	"\n" +
	"\x1dproject-root/grpc/proto.proto\"\a\n" +
	"\x05Empty\"[\n" +
	"\vChatMessage\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12 \n" +
	"\vlogicalTime\x18\x03 \x01(\x03R\vlogicalTime\"K\n" +
	"\vJoinRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12 \n" +
	"\vlogicalTime\x18\x02 \x01(\x03R\vlogicalTime\"L\n" +
	"\fLeaveRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12 \n" +
	"\vlogicalTime\x18\x02 \x01(\x03R\vlogicalTime\"^\n" +
	"\x0ePublishRequest\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12 \n" +
	"\vlogicalTime\x18\x03 \x01(\x03R\vlogicalTime2\x81\x01\n" +
	"\x0fChitChatService\x12&\n" +
	"\x04Join\x12\f.JoinRequest\x1a\f.ChatMessage\"\x000\x01\x12$\n" +
	"\aPublish\x12\x0f.PublishRequest\x1a\x06.Empty\"\x00\x12 \n" +
	"\x05Leave\x12\r.LeaveRequest\x1a\x06.Empty\"\x00B\x19Z\x17project-root/grpc;protob\x06proto3"

var (
	file_project_root_grpc_proto_proto_rawDescOnce sync.Once
	file_project_root_grpc_proto_proto_rawDescData []byte
)

func file_project_root_grpc_proto_proto_rawDescGZIP() []byte {
	file_project_root_grpc_proto_proto_rawDescOnce.Do(func() {
		file_project_root_grpc_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_project_root_grpc_proto_proto_rawDesc), len(file_project_root_grpc_proto_proto_rawDesc)))
	})
	return file_project_root_grpc_proto_proto_rawDescData
}

var file_project_root_grpc_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_project_root_grpc_proto_proto_goTypes = []any{
	(*Empty)(nil),          // 0: Empty
	(*ChatMessage)(nil),    // 1: ChatMessage
	(*JoinRequest)(nil),    // 2: JoinRequest
	(*LeaveRequest)(nil),   // 3: LeaveRequest
	(*PublishRequest)(nil), // 4: PublishRequest
}
var file_project_root_grpc_proto_proto_depIdxs = []int32{
	2, // 0: ChitChatService.Join:input_type -> JoinRequest
	4, // 1: ChitChatService.Publish:input_type -> PublishRequest
	3, // 2: ChitChatService.Leave:input_type -> LeaveRequest
	1, // 3: ChitChatService.Join:output_type -> ChatMessage
	0, // 4: ChitChatService.Publish:output_type -> Empty
	0, // 5: ChitChatService.Leave:output_type -> Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_project_root_grpc_proto_proto_init() }
func file_project_root_grpc_proto_proto_init() {
	if File_project_root_grpc_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_project_root_grpc_proto_proto_rawDesc), len(file_project_root_grpc_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_project_root_grpc_proto_proto_goTypes,
		DependencyIndexes: file_project_root_grpc_proto_proto_depIdxs,
		MessageInfos:      file_project_root_grpc_proto_proto_msgTypes,
	}.Build()
	File_project_root_grpc_proto_proto = out.File
	file_project_root_grpc_proto_proto_goTypes = nil
	file_project_root_grpc_proto_proto_depIdxs = nil
}
