// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: project-root/grpc/proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Region content of messages
// empty message for when no user input is required. Used for join- and leave requests
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_project_root_grpc_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_project_root_grpc_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_project_root_grpc_proto_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// message for when a new user joins the chat
type JoinRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When a new
	// participant X joins, the service must broadcast a message of the form:
	// "Participant X joined Chit Chat at logical time L". This message must
	// be delivered to all participants, including the newly joined one.
	JoiningUser   string `protobuf:"bytes,1,opt,name=joiningUser,proto3" json:"joiningUser,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_project_root_grpc_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_root_grpc_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_project_root_grpc_proto_proto_rawDescGZIP(), []int{1}
}

func (x *JoinRequest) GetJoiningUser() string {
	if x != nil {
		return x.JoiningUser
	}
	return ""
}

// message for when a user leaves the chat
type LeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeavingUser   string                 `protobuf:"bytes,1,opt,name=leavingUser,proto3" json:"leavingUser,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	mi := &file_project_root_grpc_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_root_grpc_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_project_root_grpc_proto_proto_rawDescGZIP(), []int{2}
}

func (x *LeaveRequest) GetLeavingUser() string {
	if x != nil {
		return x.LeavingUser
	}
	return ""
}

// message for clients to publish a new chat message
type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_project_root_grpc_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_root_grpc_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_project_root_grpc_proto_proto_rawDescGZIP(), []int{3}
}

// message for displaying a new chat message
type BroadcastMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastMessage) Reset() {
	*x = BroadcastMessage{}
	mi := &file_project_root_grpc_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastMessage) ProtoMessage() {}

func (x *BroadcastMessage) ProtoReflect() protoreflect.Message {
	mi := &file_project_root_grpc_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastMessage.ProtoReflect.Descriptor instead.
func (*BroadcastMessage) Descriptor() ([]byte, []int) {
	return file_project_root_grpc_proto_proto_rawDescGZIP(), []int{4}
}

var File_project_root_grpc_proto_proto protoreflect.FileDescriptor

const file_project_root_grpc_proto_proto_rawDesc = "" +
	"\n" +
	"\x1dproject-root/grpc/proto.proto\"\x1d\n" +
	"\aMessage\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\"/\n" +
	"\vJoinRequest\x12 \n" +
	"\vjoiningUser\x18\x01 \x01(\tR\vjoiningUser\"0\n" +
	"\fLeaveRequest\x12 \n" +
	"\vleavingUser\x18\x01 \x01(\tR\vleavingUser\"\x10\n" +
	"\x0ePublishRequest\"\x12\n" +
	"\x10BroadcastMessage23\n" +
	"\x0fChitChatService\x12 \n" +
	"\bSayHello\x12\b.Message\x1a\b.Message\"\x00B\x19Z\x17project-root/grpc;protob\x06proto3"

var (
	file_project_root_grpc_proto_proto_rawDescOnce sync.Once
	file_project_root_grpc_proto_proto_rawDescData []byte
)

func file_project_root_grpc_proto_proto_rawDescGZIP() []byte {
	file_project_root_grpc_proto_proto_rawDescOnce.Do(func() {
		file_project_root_grpc_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_project_root_grpc_proto_proto_rawDesc), len(file_project_root_grpc_proto_proto_rawDesc)))
	})
	return file_project_root_grpc_proto_proto_rawDescData
}

var file_project_root_grpc_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_project_root_grpc_proto_proto_goTypes = []any{
	(*Message)(nil),          // 0: Message
	(*JoinRequest)(nil),      // 1: JoinRequest
	(*LeaveRequest)(nil),     // 2: LeaveRequest
	(*PublishRequest)(nil),   // 3: PublishRequest
	(*BroadcastMessage)(nil), // 4: BroadcastMessage
}
var file_project_root_grpc_proto_proto_depIdxs = []int32{
	0, // 0: ChitChatService.SayHello:input_type -> Message
	0, // 1: ChitChatService.SayHello:output_type -> Message
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_project_root_grpc_proto_proto_init() }
func file_project_root_grpc_proto_proto_init() {
	if File_project_root_grpc_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_project_root_grpc_proto_proto_rawDesc), len(file_project_root_grpc_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_project_root_grpc_proto_proto_goTypes,
		DependencyIndexes: file_project_root_grpc_proto_proto_depIdxs,
		MessageInfos:      file_project_root_grpc_proto_proto_msgTypes,
	}.Build()
	File_project_root_grpc_proto_proto = out.File
	file_project_root_grpc_proto_proto_goTypes = nil
	file_project_root_grpc_proto_proto_depIdxs = nil
}
